@startuml
left to right direction
:Operstions Manager: as ops
:Stack Developer: as stackdev
:Application Developer: as dev

rectangle "H2C"  #aaffff {
  usecase "Manage Workload" as MW
  usecase "Submit Workload" as SW
  usecase "Manage Infrastructure" as MI
}

ops --> MW
ops --> SW
ops --> MI

@enduml
